version: "3.4"

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi5
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIROMENT=Development
      - ConnectionString=Server=db;Database=CARSITE;User Id=SA;Password=Password_123;MultipleActiveResultSets=true; TrustServerCertificate=True;;
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Password_123"
      - "ACCEPT_EULA=Y"
    container_name: mssql-5
    ports:
      - "1555:1433"